#!/usr/bin/env bash

file="bench/data/core.c"
bench "./target/wc-demo $file" \
    "loc -u $file" \
    "tokei --no-ignore-vcs --no-ignore $file" \
    "scc -c --no-cocomo --binary --no-gitignore --no-ignore $file" \
    "cloc $file" \
    "lang ${file}"
